"""


- 서버 실행 시 manage.py의 main() 함수가 제일 먼저 읽는 설정 파일
- 여기 작성된 내용은 프로젝트 전체에 공유된다.

Django settings for _01_django_project project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)j8wf@$%pev_9q*(mdfl9n*$8zevsyq(iu)&tu+k8xb4r&h6j3'

# 상세 오류 출력 옵션(개발 중에는 True, 운영/배포 시에는 False)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# CORS 설정 - 허용되는 도메인, IP 작성
# DEBUG = True 이고 ALLOWED_HOSTS 빈칸이면 127.0.0.1
ALLOWED_HOSTS = []


# Application definition
# - 프로젝트에서 사용할 앱을 등록하는 부분
# - Django는 한 프로젝트 안에 여러 App을 운영할 수 있다
INSTALLED_APPS = [
    'django.contrib.admin', # 관리자 사이트
    'django.contrib.auth',  # 사이트 인증, 권한
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'first.apps.FirstConfig',
    # 'second.apps.SecondConfig',
    'second', # 앱 이름만 작성 -> 'second.apps.SecondConfig' 변환
]

# View 전후에 세션, 인증, 보안 같은 공통 처리를 적용한다.
# 요청은 위->아래,  응답은 아래->위로 해당 계층을 통과한다.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL 탐색 시작 지점
ROOT_URLCONF = '_01_django_project.urls'

# render() 함수가 렌더링에 사용할 HTML 템플릿 경로를 지정하는 부분
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_01_django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 기본 DB 연결 설정 작성 부분
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
